# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wt_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QImage
from PyQt5.QtWidgets import QFileDialog, QMessageBox, QAction, QMainWindow, QSlider, QPushButton, QToolTip, QApplication, QTableWidgetItem
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

import os
import re
import pandas as pd


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 693)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameJudul = QtWidgets.QFrame(self.centralwidget)
        self.frameJudul.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frameJudul.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameJudul.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameJudul.setObjectName("frameJudul")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameJudul)
        self.verticalLayout_2.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelJudul = QtWidgets.QLabel(self.frameJudul)
        font = QtGui.QFont()
        font.setFamily("Keep Calm")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelJudul.setFont(font)
        self.labelJudul.setAlignment(QtCore.Qt.AlignCenter)
        self.labelJudul.setObjectName("labelJudul")
        self.verticalLayout_2.addWidget(self.labelJudul)
        self.frameDummy = QtWidgets.QFrame(self.frameJudul)
        self.frameDummy.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frameDummy.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameDummy.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDummy.setObjectName("frameDummy")
        self.verticalLayout_2.addWidget(self.frameDummy)
        self.LabelNama1 = QtWidgets.QLabel(self.frameJudul)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LabelNama1.setFont(font)
        self.LabelNama1.setObjectName("LabelNama1")
        self.verticalLayout_2.addWidget(self.LabelNama1)
        self.LabelNama2 = QtWidgets.QLabel(self.frameJudul)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LabelNama2.setFont(font)
        self.LabelNama2.setObjectName("LabelNama2")
        self.verticalLayout_2.addWidget(self.LabelNama2)
        self.LabelNama3 = QtWidgets.QLabel(self.frameJudul)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LabelNama3.setFont(font)
        self.LabelNama3.setObjectName("LabelNama3")
        self.verticalLayout_2.addWidget(self.LabelNama3)
        self.verticalLayout.addWidget(self.frameJudul)
        self.frameContent = QtWidgets.QFrame(self.centralwidget)
        self.frameContent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameContent.setObjectName("frameContent")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameContent)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameDokumen = QtWidgets.QFrame(self.frameContent)
        self.frameDokumen.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frameDokumen.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameDokumen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDokumen.setObjectName("frameDokumen")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameDokumen)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frameBtn = QtWidgets.QFrame(self.frameDokumen)
        self.frameBtn.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frameBtn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBtn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBtn.setObjectName("frameBtn")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameBtn)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnAdd = QtWidgets.QPushButton(self.frameBtn)
        self.btnAdd.setObjectName("btnAdd")
        self.verticalLayout_4.addWidget(self.btnAdd)
        self.btnDel = QtWidgets.QPushButton(self.frameBtn)
        self.btnDel.setObjectName("btnDel")
        self.verticalLayout_4.addWidget(self.btnDel)
        self.verticalLayout_3.addWidget(self.frameBtn)
        self.listDokumen = QtWidgets.QListWidget(self.frameDokumen)
        self.listDokumen.setObjectName("listDokumen")
        self.verticalLayout_3.addWidget(self.listDokumen)
        self.horizontalLayout.addWidget(self.frameDokumen)
        self.frameIndex = QtWidgets.QFrame(self.frameContent)
        self.frameIndex.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameIndex.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameIndex.setObjectName("frameIndex")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameIndex)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listIndex = QtWidgets.QListWidget(self.frameIndex)
        self.listIndex.setObjectName("listIndex")
        self.verticalLayout_5.addWidget(self.listIndex)
        self.horizontalLayout.addWidget(self.frameIndex)
        self.verticalLayout.addWidget(self.frameContent)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Declare Variables
        self.counter = 1
        self.listFile = []
        self.split_words = []
        self.list_stopwords = []
        self.stopped_words = []
        self.stemmed_words = []

        # Declare Function
        self.btnAdd.clicked.connect(self.doWhat)
        self.btnDel.clicked.connect(self.deleteFile)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistem Temu Kembali Informasi"))
        self.labelJudul.setText(_translate("MainWindow", "Boolean Model"))
        self.LabelNama1.setText(_translate("MainWindow", "I Putu Bayu Adhya Wiratama (1905551059)"))
        self.LabelNama2.setText(_translate("MainWindow", "Ida Ayu Oka Dewi Cahyani (1905551146)"))
        self.LabelNama3.setText(_translate("MainWindow", "Dwi Ahmad Dzulhijjah (2105551162)"))
        self.btnAdd.setText(_translate("MainWindow", "+ Add Document"))
        self.btnDel.setText(_translate("MainWindow", "- Delete Document"))

    def openFile(self):

        # Open File
        self.fileName, fileType = QFileDialog.getOpenFileName(self.centralwidget, "Open File", "", "*.txt;;All Files(*)")
        filename = os.path.basename(self.fileName)
        self.listDokumen.addItem('{}. {}'.format(self.counter, filename))
        self.listFile.append(self.fileName)

        self.counter += 1

    def tokenize(self):

        # Tokenizing words
        with open(self.fileName, 'r') as namaFile:
            for content in namaFile:
                content = content.lower()
                content = re.split(r'\W+', content)
                
                self.split_words.extend(content)
                self.split_words = list(dict.fromkeys(self.split_words))

        self.split_words.sort()

    def removeStopwords(self):

        # Stopwords
        stopwords_path = 'stopwords_pilkada.csv'

        df = pd.read_csv(stopwords_path)
        for item in df['ada']:
            self.list_stopwords.append(item)
        
        self.stopped_words = self.split_words
        for x in self.stopped_words:
            if x in self.list_stopwords:
                self.stopped_words.remove(x)
        
    def stemming(self):

        # Stemming
        factory = StemmerFactory()
        stemmer = factory.create_stemmer()

        for item in self.stopped_words:
            stemming = stemmer.stem(item)
            self.stemmed_words.append(stemming)
            
        self.stemmed_words = list(dict.fromkeys(self.stemmed_words))
        self.stemmed_words.sort()

    def printIndex(self):

        # Printing
        self.listIndex.clear()

        for item in self.stemmed_words:
            exist_file = list()
            for data in self.listFile:
                with open(data, 'r') as namaFile:
                    for isi in namaFile:
                        isi = isi.lower()
                        if item in isi:
                            exist_file.append(os.path.basename(data))
                            exist_file = list(dict.fromkeys(exist_file))
            self.listIndex.addItem('{}\t: <{}>'.format(item, exist_file))

    def doWhat(self):
        self.openFile()
        self.tokenize()
        self.removeStopwords()
        self.stemming()
        self.printIndex()

    def deleteFile(self):
        self.counter = 1
        self.listDokumen.clear()
        self.listIndex.clear()
        self.listFile.clear()
        self.split_words.clear()
        self.list_stopwords.clear()
        self.stopped_words.clear()
        self.stemmed_words.clear()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
