# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wt_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QImage
from PyQt5.uic import loadUi
from PyQt5.QtWidgets import QFileDialog, QMessageBox, QAction, QMainWindow, QSlider, QPushButton, QToolTip, QApplication, QTableWidgetItem
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

import os
import re
import pandas as pd

class Ui_MainWindow(QMainWindow):

    def __init__(self):

        QMainWindow.__init__(self)
        loadUi('wt_gui.ui', self)

        # Declare Variables
        self.counter = 1
        self.listFile = [] # List file full path
        self.split_words = [] # Tokenized words
        self.list_stopwords = [] # kamus stopwords
        self.stopped_words = [] # stopped words
        self.stemmed_words = [] # stemmed words

        self.file_tampil = [] # for process
        self.split_tampil = [] # for process
        self.stop_tampil = [] # for process
        self.stem_tampil = [] # for process

        # Declare Function
        self.btnAdd.clicked.connect(self.doWhat)
        self.btnDel.clicked.connect(self.deleteFile)
        self.btnSearch.clicked.connect(self.booleanModel)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistem Temu Kembali Informasi"))
        self.labelJudul.setText(_translate("MainWindow", "Boolean Model"))

    def openFile(self):

        # Open File
        self.fileName, fileType = QFileDialog.getOpenFileName(self.centralwidget, "Open File", "", "*.txt;;All Files(*)")
        if self.fileName not in self.listFile:
            self.listFile.append(self.fileName)

            filename = os.path.basename(self.fileName)
            self.file_tampil.append(filename)
            self.listDokumen.addItem('{}. {}'.format(self.counter, filename))

            self.counter += 1

    def tokenize(self):

        # Tokenizing words
        with open(self.fileName, 'r') as namaFile:
            for content in namaFile:
                content = content.lower()
                content = re.split(r'\W+', content)
                
                self.split_words.extend(content)
                self.split_words = list(dict.fromkeys(self.split_words))

                self.split_tampil.extend(content)
                self.split_tampil = list(dict.fromkeys(self.split_tampil))

    def showOriginal(self):
        self.listOriginal.addItem(os.path.basename(self.fileName) + ':')
        with open(self.fileName, 'r') as namaFile:
            for content in namaFile:
                self.listOriginal.addItem('   {}'.format(content))

    def removeStopwords(self):

        # Stopwords
        stopwords_path = 'stopwords_pilkada.csv'

        df = pd.read_csv(stopwords_path)
        for item in df['ada']:
            self.list_stopwords.append(item)
        
        self.stopped_words = self.split_words
        self.stop_tampil = self.split_tampil

        for x in self.stopped_words[:]:
            if x in self.list_stopwords[:]:
                self.stopped_words.remove(x)
                self.stop_tampil.remove(x)
        
        self.listStopwords.addItem(os.path.basename(self.fileName) + ':')
        self.listStopwords.addItem('   {}'.format(str(self.stop_tampil)))

    def stemming(self):

        # Stemming
        factory = StemmerFactory()
        stemmer = factory.create_stemmer()

        for item in self.stopped_words:
            stemming = stemmer.stem(item)
            self.stemmed_words.append(stemming)
        
        for item in self.stop_tampil:
            stemming = stemmer.stem(item)
            self.stem_tampil.append(stemming)
            
        self.stemmed_words = list(dict.fromkeys(self.stemmed_words))

        self.stem_tampil = list(dict.fromkeys(self.stem_tampil))

        self.listStemming.addItem(os.path.basename(self.fileName) + ':')
        self.listStemming.addItem('   {}'.format(str(self.stem_tampil)))

        self.split_tampil.clear()
        self.stop_tampil.clear()
        self.stem_tampil.clear()

    def printInverted(self):

        # Printing
        self.listInverted.clear()

        for item in range(len(self.stopped_words)):
            exist_file = list()
            for data in self.listFile:
                with open(data, 'r') as namaFile:
                    for isi in namaFile:
                        isi = isi.lower()
                        if self.stopped_words[item] in isi:
                            exist_file.append(os.path.basename(data))
                            exist_file = list(dict.fromkeys(exist_file))
            self.listInverted.addItem('{}\t: <{}>'.format(self.stemmed_words[item], exist_file))

    def printIncidence(self):

        self.items_clear()

        panjang_col = len(self.listFile)
        panjang_row = len(self.split_words)

        self.tableWidget.setColumnCount(panjang_col)
        self.tableWidget.setRowCount(panjang_row)

        self.tableWidget.setHorizontalHeaderLabels(self.file_tampil)
        self.tableWidget.setVerticalHeaderLabels(self.split_words)

        for x in range(len(self.split_words)):
            for y in range(len(self.file_tampil)):
                with open(self.listFile[y], 'r') as openFile:
                    for content in openFile:
                        if self.split_words[x] in content.lower():
                            self.tableWidget.setItem(x, y, QTableWidgetItem('1'))
                        else:
                            self.tableWidget.setItem(x, y, QTableWidgetItem('0'))             

    def items_clear(self):
        for item in self.tableWidget.selectedItems():
            newitem = QTableWidgetItem()
            self.tableWidget.setItem(item.row(), item.column(), newitem)

    def doWhat(self):
        self.openFile()
        self.tokenize()
        self.removeStopwords()
        self.stemming()
        self.showOriginal()
        self.printIncidence()
        self.printInverted()

    def deleteFile(self):
        self.counter = 1
        self.listDokumen.clear()
        self.listInverted.clear()
        self.listFile.clear()
        self.split_words.clear()
        self.list_stopwords.clear()
        self.stopped_words.clear()
        self.stemmed_words.clear()
        self.items_clear()

    def booleanModel(self):
        
        teksEdit = self.textEdit.toPlainText()
        teksEdit = re.split(r'\W+', teksEdit)

        connecting_words = []
        different_words = []
        for word in teksEdit:
            if word.lower() != 'and' and word.lower() != 'or' and word.lower() != 'not':
                different_words.append(word.lower())
            else:
                connecting_words.append(word.lower())
        
        total_files = len(self.listFile)

        zeroes_and_ones = []
        zeroes_and_ones_of_all_words = []
        for word in different_words:
            if word in self.stemmed_words:
                zeroes_and_ones = [0] * total_files
                zeroes_and_ones_of_all_words.append(zeroes_and_ones)
                
        print(different_words)
        print(connecting_words)
        print(zeroes_and_ones)
        print(zeroes_and_ones_of_all_words)

        for word in connecting_words:
            word_list1 = zeroes_and_ones_of_all_words[0]
            word_list2 = zeroes_and_ones_of_all_words[1]
            if word == "and":
                bitwise_op = [w1 & w2 for (w1,w2) in zip(word_list1,word_list2)]
                zeroes_and_ones_of_all_words.remove(word_list1)
                zeroes_and_ones_of_all_words.remove(word_list2)
                zeroes_and_ones_of_all_words.insert(0, bitwise_op);
            elif word == "or":
                bitwise_op = [w1 | w2 for (w1,w2) in zip(word_list1,word_list2)]
                zeroes_and_ones_of_all_words.remove(word_list1)
                zeroes_and_ones_of_all_words.remove(word_list2)
                zeroes_and_ones_of_all_words.insert(0, bitwise_op);
            elif word == "not":
                bitwise_op = [not w1 for w1 in word_list2]
                bitwise_op = [int(b == True) for b in bitwise_op]
                zeroes_and_ones_of_all_words.remove(word_list2)
                zeroes_and_ones_of_all_words.remove(word_list1)
                bitwise_op = [w1 & w2 for (w1,w2) in zip(word_list1,bitwise_op)]
        
        zeroes_and_ones_of_all_words.insert(0, bitwise_op);

        files = []    
        print(zeroes_and_ones_of_all_words)
        lis = zeroes_and_ones_of_all_words[0]
        cnt = 1
        for index in lis:
            if index == 1:
                files.append(self.file_tampil[cnt])
            cnt = cnt+1
        
        print(files)

app = QApplication([])
window = Ui_MainWindow()
window.show()
app.exec_()



