# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testing.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.uic import loadUi

import os
import re


class Ui_MainWindow(QMainWindow):

    def __init__(self):

        QMainWindow.__init__(self)
        loadUi('testing.ui', self)

        # Declare Variables
        self.list_file = list()
        self.file_tampil = list()
        self.split_words = list()

        # Connect Widgets
        self.pushButton.clicked.connect(self.makeTable)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def makeTable(self):
        
        self.fileName, fileType = QFileDialog.getOpenFileName(self.centralwidget, "Open File", "", "*.txt;;All Files(*)")
        
        # List File
        self.list_file.append(self.fileName)
        self.file_tampil.append(os.path.basename(self.fileName))

        # Tokenize
        with open(self.fileName, 'r') as namaFile:
            for content in namaFile:
                content = content.lower()
                content = re.split(r'\W+', content)
                
                self.split_words.extend(content)
                self.split_words = list(dict.fromkeys(self.split_words))
        
        print('self.file_tampil :', self.file_tampil)
        # print('self.split_words :', self.split_words)

        # Make Table
        self.items_clear()

        panjang_col = len(self.list_file)
        panjang_row = len(self.split_words)

        self.tableWidget.setColumnCount(panjang_col)
        self.tableWidget.setRowCount(panjang_row)

        self.tableWidget.setHorizontalHeaderLabels(self.file_tampil)
        self.tableWidget.setVerticalHeaderLabels(self.split_words)

        for x in range(len(self.split_words)):
            for y in range(len(self.file_tampil)):
                with open(self.list_file[y], 'r') as openFile:
                    for content in openFile:
                        if self.split_words[x] in content.lower():
                            self.tableWidget.setItem(x, y, QTableWidgetItem('yes'))
                        else:
                            self.tableWidget.setItem(x, y, QTableWidgetItem('no'))

    def items_clear(self):
        for item in self.tableWidget.selectedItems():
            newitem = QtGui.QTableWidgetItem()
            self.tableWidget.setItem(item.row(), item.column(), newitem)
        
app = QApplication([])
window = Ui_MainWindow()
window.show()
app.exec_()